branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    secure: MVPPwbr1huDw6pQ/MoXZlieQul6DfF5zOhI+i/HmeUbRSigibHRRNvLkBr3Pejc2FOwDUe9RDlqfRxoWYUsp1dTzxqZwHdf6TrVnEJ6R4GqwCbAEG+CzV8AnYI2qiRJVxvW1JrzmvPJPENQzzvXjlZDOVguHTebgAv1kHdvYDgo=
before_install:
- git submodule update --init --recursive
after_success: chmod +x deploy.sh && ./deploy.sh
